<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>099a1ac5-971c-475e-8e23-b5865c98d81e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_qa_submit_umrah</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#qa-submit-umrah</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qa-submit-umrah') and equals(@text,'\u0625\u0639\u0627\u062f\u0629 \u0625\u0631\u0633\u0627\u0644 \u0644\u0646\u0638\u0627\u0645 \u0627\u0644\u0639\u0645\u0631\u0629')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qa-submit-umrah</value>
        <webElementGuid>9a2e9236-3b57-4741-9440-4cac64f53ae3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>إعادة إرسال لنظام العمرة</value>
        <webElementGuid>9a2e9236-3b57-4741-9440-4cac64f53ae3</webElementGuid>
    </webElementProperties>
</WebElementEntity>