<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>80bf61e7-44d7-4977-ae3d-0b5640f2541d</elementGuidId>
    <imagePath></imagePath>
    <name>button</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/form[1]/div[8]/button[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-brand\\ btn-md\\ btn-tall\\ btn-wide\\ kt-font-bold\\ kt-font-transform-u\\ js-next-btn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'\u0627\u0644\u062e\u0637\u0648\u0629 \u0627\u0644\u062a\u0627\u0644\u064a\u0629')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>الخطوة التالية</value>
        <webElementGuid>9a2e9236-3b57-4741-9440-4cac64f53ae3</webElementGuid>
    </webElementProperties>
</WebElementEntity>