<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b8c0d008-e3f0-4f45-bd46-78362c670b90</elementGuidId>
    <imagePath></imagePath>
    <name>input_select_arrival_flight</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/form[1]/div[5]/div[2]/div[1]/div[1]/div[3]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[7]/label[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role="row"]:nth-child(2) [type="radio"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'select-arrival-flight') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>select-arrival-flight</value>
        <webElementGuid>b98f706a-d6af-4978-97a1-e185763b2846</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>b98f706a-d6af-4978-97a1-e185763b2846</webElementGuid>
    </webElementProperties>
</WebElementEntity>